# Generated by Django 4.0.4 on 2022-07-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('est_days', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('deadline_val', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('est_days', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
